export type DeepPartial<T> = {
  [P in keyof T]?: T[P] extends Array<infer U>
    ? Array<DeepPartial<U>>
    : T[P] extends ReadonlyArray<infer U>
    ? ReadonlyArray<DeepPartial<U>>
    : DeepPartial<T[P]>
}

export interface IConfigApp {
  port: number
  nodeEnv?: string
  appKey: string
  databaseUrlSql?: string
  databaseUrlMongo?: string
  internalAccessToken?: string
  redisUrl: string
  appUrl?: string
  base_url?: string
  appMode?: number
  logDir: string
  origin: string
  credentials: boolean
  dbUsername: string
  dbPassword: string
  dbDatabase: string
  dbHost: string
  firebaseServerKey: string
  defaultOtp: number
  razorpayKey: string
  razorpaySecret: string
  razorpaySubscriptionPlanId: string
  phpApiKey: string
  phpApiSecret: string
  bravoApiKey: string
  bravoSenderName: string
  bravoFrom: string
  asferaApiKey: string
  asferaApiSecret: string
  preprodBaseUrl: string
  prodBaseUrl: string
  devBaseUrl: string
  msg91AuthKey: string
  dsModeUat?: number
  cibilCredentials?: CibilCredentials
  aws_s3_access_key_id: string
  aws_s3_seceret_access_key: string
  aws_s3_region: string
  aws_s3_bucket_name: string
  decentro_api: string
  decentro_client_id: string
  decentro_client_secret: string
  decentro_module_secret: string
  decentro_eAadharApi: string
  decentro_access_token_Api: string
  digitap_live_env_url: string
  digitap_live_client_id: string
  digitap_live_client_secret: string
  digitap_live_env_deviceAnalytics_url: string
  digitap_dev_env_url: string
  digitap_dev_client_id: string
  digitap_dev_client_secret: string
  digitap_dev_env_deviceAnalytics_url: string
  surePassApi: string
  surePassToken: string
  msg91SmsAuthKey: string
  smsTemplateId: string
  jwtSecret: string
  aws_region_ses: string
  aws_access_key_id_ses: string
  aws_secret_access_key_ses: string
  mail_for_ses: string
  mailServiceProvider: string
  razorpayDisbursalKeyId: string
  razorpayDisbursalKeySecret: string
  razorPayBaseUrl: string
  defaultUserId: string
  bankConnectDevApiKey: string
  bankConnectDevServerHash: string
  bankConnectLiveApiKey: string
  bankConnectLiveServerHash: string
  dpdInterest: string
  dpdPenalty: string
  dpdPenaltyGstPercentage: string
  ipcDpdInterest: string
  leadRejectedDays: string
  gst: string
  jwtPrivateKey: string
  jwtPublicKey: string
  dbTimeZone: string
  dbPort: string
  webengageLicenseCode: string
  webengageApiKey: string
  webengageHost: string
  webengage: boolean
  stagingBaseUrl: string
  reloanMax: string
  emiMaxAmount: string
  bulkMandateTime: string
  verifyPaymentRazorpayCron: string
  razorpayPennyKeyId: string
  razorpayPennyKeySecret: string
  companyAccountNo: string
  emandateAmount: string
  decentroBaseUrl: string
  nodeApiKey: string
  nodeApiSecret: string
  templateIdSmsOtp: string
  entityIdSmsOtp: string
  notificationBaseUrl: string
  profileLink: string
  cibilLink: string
  finboxLink: string
  audioLink: string
  otpSenderEmail: string
  experianHardPullUsername: string
  experianHardPullPassword: string
  experianHardPullMethod: string
  experianHardPullUrl: string
  experianHardPullContentType: string
  experianHardPullCookie: string
  defaultAccountNo: string
  kamakshiMoneyApiKey: string
  blacklistCustomerWebhook: string
  dbReplicaHost: string
  dbReplicaPort: string
  dbReplicaUsername: string
  dbReplicaPassword: string
  dbReplicaDatabase: string
}
export interface CibilCredentials {
  key: string
  cert: string
  passphrase: string
  apiKey: string
  custRefId: string
  apiBase: string
  siteName: string
  accountName: string
  accountCode: string
  productConfigurationId: string
  creditViewUrl: string
}
