export enum LeadLogApiType {
  IDENTITY = "identity",
  AADHAR_V2_GENERATE_OTP = "aadhaar-v2-generate-otp",
  AADHAR_V2_SUBMIT_OTP = "aadhaar-v2-submit-otp",
  SUREPASS_EAADHAR = "surepass_eaadhaar",
  SUREPASS_INITIATE_AADHAR = "surepass_digilocker_initiate_session",
  DIGILOCKER_EAADHAR = "digilocker_eaadhaar",
  DIGILOCKER_INITIATE_AADHAR = "digilocker_initiate_session",
  DIGILOCKER_ACCESS_TOKEN = "digilocker_access_token",
  PAN_COMPREHENSIVE = "pan-comprehensive",
  XLSX_REPORT = "xlsx_report",
  PREDICTORS = "predictors",
  BANKING_SURROGATE = "banking_surrogate",
  BUREAU_SURROGATE = "bureau_sagorate",
  RAJAT_API_BUREAU = "rajat_api_bureau",
  FOURTH_LOAN = "Fourth_loan_amount_check",
  PAN_COMPREHENSIVE_DIGITAP = "pan-comprehensive",
  SUREPASS_DIGILOCKER_STATUS = "surepass_digilocker_status",
  SUREPASS_DIGILOCKER_DOCUMENT_LIST = "surepass_digilocker_document_list",
  SUREPASS_DIGILOCKER_DOCUMENT_DOWNLOAD = "surepass_digilocker_document_download",
  SUREPASS_DIGILOCKER_EAADHAAR = "surepass_digilocker_eaadhaar",
  FINBUD_CREDIT_REPORT = "finbud_credit_report",
  SUREPASS_FACE_MATCH = "surepass_face_match",
  DIGITAP_FACE_MATCH = "digitap_face_match",
  SUREPASS_BANK_VERIFICATION = "surepass_bank_verification",
  DIGITAP_PENNY_DROP = "digitap_penny_drop",
  CREDFORGE_BUREAU_RAJAT = "credforge_bureau_rajat",
  CREDFORGE_BUREAU_BANK_BRE_RAJAT = "credforge_bureau_bank_bre_rajat",
  FINBOX_SESSION_INITIATE = "finbox_session_initiate",
  EXPERIAN_HARD_PULL = "experian_hard_pull",

  FINBOX_UPLOAD_STATUS = "finbox_upload_status",
  FINBOX_SESSION_PROGRESS = "finbox_session_progress",
  FINBOX_SESSION_STATUS = "finbox_session_status",
  FINBOX_SESSION_INSIGHT = "finbox_session_insight",

  DIGITAP_ESIGN = "digitap_esign",
  DIGITAP_INITIATE_DIGILOCKER = "digitap_initiate_digilocker",
  DIGITAP_GET_DIGILOCKER_DETAILS = "digitap_get_details",

  CRIF_SOFTPULL_INITIATE = "crif_softpull_initiate",
  CRIF_SOFTPULL_AUTHORIZED = "crif_softpull_authorized",
  CRIF_SOFTPULL_REPORT = "crif_softpull_report",

  BUREAU_BRE = "bureau_bre",
  BANK_BRE = "bank_bre",

  DIGITAP_AA_GENERATE_URL = "digitap_aa_generate_url",
  DIGITAP_AA_STATUS_CHECK = "digitap_aa_status_check",
  DIGITAP_AA_REPORT = "digitap_aa_report",
}
