export enum ChatbotContentType {
  FAQ = 'FAQ',
  NUDGE = 'Nudge',
}

export enum ChatbotQueryCategory {
  TECHNICAL_ISSUES = 'TECHNICAL_ISSUES',
  AUTHENTICATION_VERIFICATION = 'AUTHENTICATION_VERIFICATION',
  PROCESS_WORKFLOW = 'PROCESS_WORKFLOW',
  APPROVAL_DISBURSEMENT = 'APPROVAL_DISBURSEMENT',
  OTHER = 'OTHER',
  UNCATEGORIZED = 'UNCATEGORIZED',
}

export enum ChatbotQueryStatus {
  PENDING = 'PENDING',
  RESOLVED = 'RESOLVED',
}

export enum ChatbotStageKey {
  ONBOARDING_WELCOME = 'ONBOARDING_WELCOME',
  USER_NAME_EMAIL_ENTRY = 'USER_NAME_EMAIL_ENTRY',
  KYC_PAN_ENTRY = 'KYC_PAN_ENTRY',
  KYC_AADHAR_VERIFY = 'KYC_AADHAR_VERIFY',
  KYC_AADHAR_OTP_VERIFY = 'KYC_AADHAR_OTP_VERIFY',
  LOAN_PURPOSE_SELECTION = 'LOAN_PURPOSE_SELECTION',
  LOAN_AMOUNT_ENTRY = 'LOAN_AMOUNT_ENTRY',
  PERSONAL_DETAILS_ENTRY = 'PERSONAL_DETAILS_ENTRY',
  EDUCATION_DETAILS_ENTRY = 'EDUCATION_DETAILS_ENTRY',
  EMPLOYMENT_DETAILS_ENTRY = 'EMPLOYMENT_DETAILS_ENTRY',
  PAYMENT_MODE_SELECTION = 'PAYMENT_MODE_SELECTION',
  COMPANY_NAME_ENTRY = 'COMPANY_NAME_ENTRY',
  INDUSTRY_DESIGNATION_ENTRY = 'INDUSTRY_DESIGNATION_ENTRY',
  MONTHLY_INCOME_ENTRY = 'MONTHLY_INCOME_ENTRY',
  WORK_EXPERIENCE_ENTRY = 'WORK_EXPERIENCE_ENTRY',
  SALARY_DATE_SELECTION = 'SALARY_DATE_SELECTION',
  RESIDENCE_TYPE_SELECTION = 'RESIDENCE_TYPE_SELECTION',
  ADDRESS_ENTRY = 'ADDRESS_ENTRY',
  BANK_STATEMENT_UPLOAD = 'BANK_STATEMENT_UPLOAD',
  LOAN_REVIEW_SCREEN = 'LOAN_REVIEW_SCREEN',
  LOAN_SELECTION_SCREEN = 'LOAN_SELECTION_SCREEN',
  LOAN_APPROVAL_SCREEN = 'LOAN_APPROVAL_SCREEN',
  REFERENCES_ENTRY = 'REFERENCES_ENTRY',
  SELFIE_UPLOAD = 'SELFIE_UPLOAD',
  BANK_DETAILS_SHARE = 'BANK_DETAILS_SHARE',
  E_MANDATE_SETUP = 'E_MANDATE_SETUP',
  BANK_SELECTION_FOR_DISBURSAL = 'BANK_SELECTION_FOR_DISBURSAL',
  KFS_VIEW = 'KFS_VIEW',
  REPAYMENT_SCREEN = 'REPAYMENT_SCREEN',
  REPAYMENT_TYPE_SELECTION = 'REPAYMENT_TYPE_SELECTION',
  // ELIGIBILITY_CHECK_FORM = 'ELIGIBILITY_CHECK_FORM',
  // BANK_DETAILS_ENTRY = 'BANK_DETAILS_ENTRY',
  // LOAN_DISBURSEMENT_STATUS = 'LOAN_DISBURSEMENT_STATUS',
}
