export const masterPermission = {
  Collection: {
    Closed: 'collection/closed',
    Settlement: 'collection/settlement',
    BulkMandateCharge: 'bulk-emandate-charge',
    AddNotRequired: 'add_not_required',
    PaydayPaymentPending: 'payday_payment_pending',
    PaydayPaymentPendingEMI: 'payday_payment_pending_emi',
    DndList: 'dnd_list',
    PartPayment: 'collection/part_payment',
    WaiveOff: 'waive_off',
    // icon: "MdOutlineAutoMode",
    // iconColor: "#fbe165",
    // link: "/collection",
  },
  Disbursal: {
    PayoutsPending: 'payouts-pending',
    DisbursalApproved: 'disbursal-approved',
    BankUpdate: 'disbursal/bank_update',
    Disbursed: 'disbursal/disbursed',
    FailedDisbursal: 'failed_disbursal',
    WaiveOff: 'waive_off',
    BankUpdateRejected: 'disbursal/bank_update_rejected',
    MannualDisbursal: 'manual_disbursal',
    // icon: "MdLibraryBooks",
    // iconColor: "#FA26A0",
    // link: "/disbursal",
  },
  Credit: {
    Approved: 'credit/approved',
    Rejected: 'credit/rejected',
    Hold: 'credit/hold',
    NotRequired: 'credit/not_required',
  },
  Sanction: {
    ApprovedProcess: 'sanction/approved_process',
    RejectedProcess: 'sanction/rejected_process',
    HoldProcess: 'sanction/hold_process',
    NotRequiredProcess: 'sanction/not_required_process',
  },
  Lead: {
    FreshLead: 'fresh-lead',
    Callback: 'callback',
    NotInterested: 'not-interested',
    NoAnswer: 'no-answer',
    Duplicate: 'duplicate',
    DNC: 'dnc',
    IncompleteDocuments: 'incomplete-documents',
    Interested: 'interested',
    DocumentReceived: 'document-received',
    Blacklisted: 'blacklisted',
    AllLeads: 'all_leads',
    NewFlowLeads: 'newflow_leads',
    NotEligibleLeads: 'not_eligible_leads',
    NotCompletedLeads: 'not_completed_leads',
    LeadAllocate: 'lead_allocate',
    AgainNoLoan: 'again_no_loan',
  },
  Customer: {
    CustomerList: 'customer_list',
    LeadCustomerProfile: 'lead_customer_profile',
    CustomerDetail: 'customer_detail',
    Contact: 'contact',
    CustomerListMobile: 'customer-list-mobile',
    CustomerListEmail: 'customer-list-email',
    CustomerListPan: 'customer-list-pan',
    BreRules: 'bre-rules',
  },
  Management: {
    BreRules: 'bre-rules',
    ManagementUserList: 'management_user_list',
    AutoDisbStatus: 'auto_disb_status',
    UserListAdd: 'user_list_add',
    UserListEdit: 'user_list_edit',
    ManagementLoginLogs: 'management_login_logs',
    ManagementWhitelistIP: 'management_whitelistip',
    RepaydateHoliday: 'repaydate_holiday',
    ManagementCustomerList: 'management_customer_list',
    SendWhatsappStatus: 'send_whatsapp_status',
    CustomerPennyDropList: 'customer_penny_drop_list',
    WhitelistIPDelete: 'whitelistip_delete',
    ProceedNameMissmatch: 'proceed_name_missmatch',
    ProceedNameMissmatchFinbox: 'proceed_name_missmatch_finbox',
    CustomerFinboxList: 'customer_finbox_list',
    CustomerDataEditRepay: 'customer_data_edit_repay',
    RepaydateHolidayDelete: 'repaydate_holiday_delete',
    PaymentModeChange: 'payment_mode_change',
    QueryListDownload: 'query_list_download',
    RolesListView: 'roles_list_view',
    PermissionsListView: 'permissions_list_view',
    SourcingPartners: 'sourcing_partners',
    RepaymentGatewayType: 'repayment_gateway_type',
    ManualSelfieVerification: 'manual_selfie_verification',
    // icon: "MdSettings",
    // iconColor: "#38d75e",
    // link: "/management",
  },
  LeadCustomerProfile: {
    StopLeadAssign: 'stoplead_assign',
    SendNocMail: 'send_noc_mail',
    SaveAgreement: 'save_agreement',
    SendAllignVisitMail: 'send_allign_visit_mail',
    LoanApplyView: 'loan-apply-view',
    EmpView: 'emp-view',
    RefView: 'ref-view',
    CreditView: 'credit-view',
    EmView: 'em-view',
    DisbursalView: 'disbursal-view',
    LoanView: 'loan-view',
    RemarkView: 'remark-view',
    CollectionView: 'collection-view',
    PaymentModeUpdate: 'payment_mode_update',
    AddressView: 'address-view',
    AddDocuments: 'addDocuments',
    KycVideo: 'Kyc_video',
    AddBankAccount: 'addbank_account',
    BreRules: 'bre-rules',
  },
  FormAction: {
    Transaction: 'transection',
    DownloadAccess: 'download_access',
    DisbursementAutoload: 'disbursement_autoload',
  },
  CollectionManager: {
    CollectionApproval: 'collection_manager/collection_approval',
    CollectionWaiveOff: 'collection_manager/collection_waive_off',
    CollectionApproved: 'collection_manager/collection_approved',
    CollectionRejected: 'collection_manager/collection_rejected',
    OnlineCollectionPending: 'online_collection_pending',
    CollectionManagerUpdate: 'collection_manager_update',
    // icon: "MdCollectionsBookmark",
    // iconColor: "#d691eb",
    // link: "/collection-manager",
  },
  LeadProfileDetails: {
    CreditChangeStatus: 'credit-change-status',
    CreditView: 'credit-view',
    DisbursalAdd: 'disbursal-add',
    DisbursalView: 'disbursal-view',
    DisbursalUpdate: 'disbursal-update',
    DisbursalUpdateRazorpay: 'disbursal-update-razorpay',
    DisbursalUpdatePayFail: 'disbursal-update-pay-fail',
    LoanView: 'loan-view',
    RemarkAdd: 'remark-add',
    RemarkView: 'remark-view',
    CollectionAdd: 'collection-add',
    CollectionView: 'collection-view',
    DocumentAdd: 'document-add',
    DocumentView: 'document-view',
    EmView: 'em-view',
    EmCh: 'em-ch',
    LoanApplyView: 'loan-apply-view',
    AddressAdd: 'address-add',
    AddressView: 'address-view',
    EmpAdd: 'emp-add',
    EmpView: 'emp-view',
    RefAdd: 'ref-add',
    RefView: 'ref-view',
    CreditAdd: 'credit-add',
    CreditEdit: 'credit-edit',
    LinkedPanAadhaarRetry: 'linked_pan_aadhaar_retry',
    AddCollectionFollowup: 'add_collection_followup',
    AddSanctionFollowup: 'add_sanction_followup',
    ViewSanctionFollowup: 'view_sanction_followup',
    ViewBlacklistCustomer: 'view_blacklist_customer',
  },
  Report: {
    TotalLeadData: 'total-lead-data',
    CollectionReportsDispDisb: 'collection-reports-disp-disb',
    AllCompReports: 'all-comp-reports',
    FollowUp: 'follow-up',
    CollectionBucket: 'collection-bucket',
    CollectionManager: 'collection-manager',
    OnlineManager: 'online-manager',
    NoLoan: 'noloan',
    ReportAllLead: 'report_all_lead',
    NewVsRepeat: 'new_vs_repeat_collection_report',
    TlTellecaller: 'tl_tellecaller',
    TlTellecallerLeadAssign: 'tl_tellecaller_lead_assign',
    MomRepeatLoan: 'mom_repeat_loan',
    NotCompletedReport: 'not_completed_report',
    ManualApproveProcess: 'manual_approve_process',
    FullAutoTransition: 'full_auto_transition',
    SalariedVsSelfemployee: 'salaried_vs_selfemployee',
    Rejection: 'rejection',
    SettlementReport: 'settlement-report',
    ApprovedProcessTransition: 'approved-process-transition',
    LeadsAccrossAllStages: 'leads-accross-all-stages',
    NewPlusExisting: 'new_plus_existing',
    RepeatDpdReport: 'repeat_dpd_report',
    EodReport: 'eod_report',
    ReportCallingReport: 'report_calling_report',
    ReportCreditReport: 'report_credit_report',
    ReportCollectionReport: 'report_collection_report',
    ReportCollectionReport2: 'report_collection_report2',
    ReportTellecallerCollection: 'report_tellecaller_collection',
    DateWiseLeadReport: 'date_wise_lead_report',
    OutstandingDatewise: 'outstanding_datewise',
    ReportDisbursedDataDownload: 'report_disbursed_data_download',
    ReportPaydayPending: 'report_payday_pending',
    AgentPerformanceReport: 'agent_performance_report',
    QueryList: 'query_list',
    ReportDisbursedData: 'report_disbursed_data',
    ReportCollectionData: 'report_collection_data',
    ReportCollectionEMIData: 'report_collection_emi_data',
    AppDisbursal: 'app_disbursal',
    IssueList: 'issue_list',
    EmployeeReport: 'employee_report',
    CustomerFeedback: 'customer_feedback',
    BookedCallerReport: 'booked-caller-report',
    CreditManagerProductivity: 'credit_manager_productivity',
    NotComp: 'not_comp',
    AppM: 'app_m',
    ColRef: 'col_ref',
    PennyDrop: 'penny_drop',
    BulkAlo: 'bulk_alo',
    ToCreTr: 'to_cre_tr',
    FinUrl: 'fin_url',
    IssueType: 'issue_type',
    CrmFunnel: 'crm_funnel',
    BreVersions: 'bre_versions',
    FinboxBankAccount: 'finbox_bank_account',
    RepeatcaseApprovedProcess: 'repeatcase_approvedprocess',
  },
  Complaints: {
    ComplaintList0: 'complaint_list/0',
    ComplaintList1: 'complaint_list/1',
    ComplaintList2: 'complaint_list/2',
  },
  FieldsOfficer: {
    FieldOfficer: 'field_officer',
    FieldOfficerProfile: 'field_officer_profile',
    FieldOfficerWork: 'field_officer_work',
    FieldOfficerNotification: 'field_officer_notification',
  },
  DashboardReports: {
    CallR: 'call_r',
    SenctionR: 'senction_r',
    CreditR: 'credit_r',
    DisbR: 'disb_r',
    TowR: 'tow_r',
    MonwR: 'monw_r',
    LeadwR: 'leadw_r',
  },
  CibilReports: {
    Cibil1: 'cibil1',
    Cibil2: 'cibil2',
    CibilData: 'cibil_data',
    Cibil1Data: 'cibil1_data',
    CibilDown: 'cibildown',
    CollR: 'coll_r',
  },
  LogsReport: {
    LeadsApiLog: 'leads_api_log',
    RazorpayApiLog: 'razorpay_api_log',
    RazorpayApiDetail: 'razorpay_api_detail',
    AllApiLog: 'all_api_log',
    KaleyraLogs: 'kaleyra_logs',
    KaleyraLogDetail: 'kaleyra_log_detail',
    LeadsApiLogDetail: 'leads_api_log_detail',
    BreDetailView: 'bre_detail_view',
    ChatLog: 'chat_log',
    ShowBre: 'show_bre',
    ChatLogDetail: 'chat_log_detail',
    DiallerLog: 'dialler_log',
    InstallApp: 'install_app',
    WhatsappApiLog: 'whatsapp_api_log',
    SendInblueApiLog: 'send_inblue_api_log',
    LoginDeviceDetail: 'login_device_detail',
    NachPaymentLog: 'nach_payment_log',
    CronJob: 'cron_job',
    MasterCron: 'master_cron',
  },
  Settings: {
    BureauSetting: 'bureau_setting',
    MaxLoanAmountBypass: 'max_loan_amount_bypass',
    PayoutsAccountValidation: 'payouts_account_validation',
    PayoutsAccountCheck: 'payouts_account_check',
    LendingPartnerLeads: 'lending_partner_leads',
    BureauSettingView: 'bureau_setting_view',
  },
  StaticIP: {
    StaticIP: 'static_ip',
    StaticIPAdd: 'static_ip_add',
    StaticIPDelete: 'static_ip_delete',
  },
  RequestRefund: {
    RequestForRefund: 'request_for_refund',
    RefundList: 'refund_list',
    RefundReport: 'refund_report',
  },
  General: {
    BlacklistedCustomers: 'blacklisted_customers',
    BlacklistedPancard: 'blacklisted_pancard',
    ThirdPartyDowntime: 'third_party_downtime',
    BankingSurrogate: 'banking_surrogate',
    CustomerCallbackRequest: 'customer_callback_request',
    DayWiseApprovedReport: 'day_wise_approved_report',
    CallerLead: 'caller_lead',
  },
}

export const phpToReactRouteMap: { [key: string]: string } = {
  '/crm_dashboard': '/',
  '/management_user_list': '/crm-management/users',
  '/management_login_logs': '/crm-management/logins',
  '/management_whitelistip': '/crm-management/ipwhite-listing',
  '/roles_list_view': '/crm-management/roles-list',
  '/permissions_list_view': '/crm-management/permission-list',
  '/sourcing_partners': '/crm-management/sourcing-partners',

  '/repaydate_holiday': '/repaydate_holiday',
  '/auto_disb_status': '/auto_disb_status',
  '/repayment_gateway_type': '/repayment_gateway_type',

  '/management_customer_list': '/lead-actions/repayment-date-manager',
  '/customer_penny_drop_list': '/lead-actions/name-mismatch-manager',
  '/manual_selfie_verification': '/lead-actions/manual-selfie-verification',
  '/payment_mode_change': '/lead-actions/payment-mode-manager',

  '/payday_payment_pending': '/collection/pending-collection',
  '/payday_payment_pending_emi': '/collection/payday-payment-pending-emi',
  '/dnd_list': '/collection/dnd-customer',
  '/collection/closed': '/collection/closed',
  '/collection/part_payment': '/collection/part-paid',
  '/waive_off': '/collection/waived-off',
  '/collection/settlement': '/collection/settled',
  '/bulk-emandate-charge': '/collection/bulk-emandate',
  '/add_not_required': '/collection/add-not-required',

  '/collection_manager/collection_approval': '/collection-manager/approval-pending',
  '/collection_manager/collection_approved': '/collection-manager/approved',
  '/collection_manager/collection_rejected': '/collection-manager/rejected',

  '/report_all_lead': '/report/all_lead_report',
  '/quick_reports': '/report/quick-reports/',
  '/report_collection_report2': '/report/date_wise_collection_report',
  '/date_wise_lead_report': '/report/date_wise_lead_report',
  '/report_payday_pending': '/report/date_wise_pending_payment_report',
  '/customer_feedback': '/report/customer_feedback_report',
  '/refund_report': '/report/refund_report',
  '/issue_list': '/report/app_issue_list_report',
  '/report_disbursed_data': '/report/disbursed_data_report',
  '/report_collection_data': '/report/collection_data_report',
  '/report_collection_emi_data': '/report/collection_emi_data_report',
  '/lending_partner_leads': '/report/lending_partner_leads_report',
  '/credit_modification_report': '/report/credit-modification-report',
  '/credit_modification_report_summary': '/report/credit-modification-report-summary',

  '/customer_list': '/customers',

  '/customer_callback_request': '/customer-callback-request',

  '/all_leads': '/all-leads',
  '/hot_leads': '/hot-leads',
  '/credit_leads': '/credit-leads',
  '/sanction_leads': '/sanction-leads',

  '/sanction/approved_process': '/sanction-leads',
  '/sanction/rejected_process': '/sanction-leads',
  '/sanction/hold_process': '/sanction-leads',
  '/sanction/not_required_process': '/sanction-leads',

  '/credit/approved': '/credit-leads',
  '/credit/rejected': '/credit-leads',
  '/credit/hold': '/credit-leads',
  '/credit/not_required': '/credit-leads',

  '/disbursal/bank_update': '/disbursal/bank_update',
  '/disbursal/disbursed': '/disbursal/disbursed',
  '/disbursal/bank_update_rejected': '/disbursal/bank_update_rejected',
  // '/manual_disbursal': '/manual_disbursal',

  '/settlement-report': '/settlement-report',

  '/leads_api_log': '/logs/api-logs',
  '/chat_log': '/logs/chat-logs',
  '/razorpay_api_log': '/logs/razorpay-logs',
  '/kaleyra_logs': '/logs/kaleyra-logs',
  '/install_app': '/logs/app-installations',
  '/whatsapp_api_log': '/logs/whatsapp-logs',
  '/send_inblue_api_log': '/logs/send-inblue-logs',
  '/dialler_log': '/logs/dialer-logs',
  '/blacklisted_customers': '/blacklist/customers',
  '/blacklisted_pancard': '/blacklist/pancard',
}
export const masterPermissionSideBar = {
  Dashboard: {
    Dashboard: '/',
  },
  CRMManagement: {
    Users: 'management_user_list',
    Logins: 'management_login_logs',
    IpWhitelisting: 'management_whitelistip',
    RolesList: 'roles_list_view',
    PermissionsList: 'permissions_list_view',
    SourcingPartners: 'sourcing_partners',
    icon: 'MdSettings',
    iconColor: '#38d75e',
    link: '/management',
  },
  AppManagement: {
    HolidayList: 'repaydate_holiday',
    AutoDisbursalStatus: 'auto_disb_status',
    RepaymentGatewayType: 'repayment_gateway_type',
    icon: 'MdOutlineAdsClick',
    iconColor: '#ecf56e',
    link: '/repaydate_holiday',
  },
  LeadActions: {
    RepaymentDateManager: 'management_customer_list',
    NameMismatchManager: 'customer_penny_drop_list',
    ManualSelfieVerification: 'manual_selfie_verification',
    PaymentModeManager: 'payment_mode_change',
    icon: 'MdAttractions',
    iconColor: '#5bebe8',
    link: '/lead-actions',
  },
  Collection: {
    PendingCollection: 'payday_payment_pending',
    EMIPendingCollection: 'payday_payment_pending_emi',
    DNDCustomer: 'dnd_list',
    Closed: 'collection/closed',
    PartPaid: 'collection/part_payment',
    WaivedOff: 'waive_off',
    Settled: 'collection/settlement',
    BulkEMandate: 'bulk-emandate-charge',
    AddNotRequired: 'add_not_required',
    icon: 'MdOutlineAutoMode',
    iconColor: '#fbe165',
    link: '/collection',
  },
  CollectionManager: {
    ApprovalPending: 'collection_manager/collection_approval',
    Approved: 'collection_manager/collection_approved',
    Rejected: 'collection_manager/collection_rejected',
    icon: 'MdCollectionsBookmark',
    iconColor: '#d691eb',
    link: '/collection-manager',
  },
  Reports: {
    AllLeadsReport: 'report_all_lead',
    QuickReports: 'quick_reports',
    DateWiseCollectionReport: 'report_collection_report2',
    DateWiseLeadReport: 'date_wise_lead_report',
    DateWisePendingPaymentReport: 'report_payday_pending',
    CustomerFeedback: 'customer_feedback',
    RefundReport: 'refund_report',
    AppIssuesReport: 'issue_list',
    DisbursalData: 'report_disbursed_data',
    CollectionData: 'report_collection_data',
    CollectionEmiData: 'report_collection_emi_data',
    LendingPartnerLeadsReport: 'lending_partner_leads',
    CreditModificationReport: 'credit_modification_report',
    CreditModificationReportSummary: 'credit_modification_report_summary',
    icon: 'MdEditDocument',
    iconColor: '#7e3dd4',
    link: '/report',
  },
  Cibil: {
    CibilData: '/cibil_data',
    icon: 'FaUser',
    iconColor: '#9D56F7',
    link: '/cibil_data',
  },
  Customers: {
    Customers: 'customer_list',
    icon: 'MdOutlineGroups2',
    link: '/customers',
    iconColor: '#25bddb',
  },
  CallbackRequest: {
    CallbackRequest: 'customer_callback_request',
    icon: 'MdOutlinePhoneCallback',
    link: '/callback-request',
    iconColor: '#2BB3D8', //sky blue
  },
  Leads: {
    AllLeads: 'all_leads',
    HotLeads: 'hot_leads',
    CreditLeads: 'credit_leads',
    SanctionLeads: 'sanction_leads',
    icon: 'MdGroup',
    iconColor: '#f69a5b',
    link: '/leads',
  },
  Disbursal: {
    BankUpdate: 'disbursal/bank_update',
    Disbursed: 'disbursal/disbursed',
    BankUpdateRejected: 'disbursal/bank_update_rejected',
    //ManualDisbursal: 'manual_disbursal',
    icon: 'MdLibraryBooks',
    iconColor: '#FA26A0',
    link: '/disbursal',
  },
  CollectionSetting: {
    SettlementReport: 'settlement-report',
    icon: 'MdOutlineSettingsSuggest',
    iconColor: '#9D56F7',
    link: 'settlement-report',
  },
  Logs: {
    ApiLogs: 'leads_api_log',
    ChatLogs: 'chat_log',
    RazorpayLogs: 'razorpay_api_log',
    KaleyraLogs: 'kaleyra_logs',
    AppInstallations: 'install_app',
    WhatsappLogs: 'whatsapp_api_log',
    SendInBlueLogs: 'send_inblue_api_log',
    DialerLogs: 'dialler_log',
    icon: 'MdFileOpen',
    iconColor: '#e05c48',
    link: '/logs',
  },
  Blacklisted: {
    Customers: 'blacklisted_customers',
    Pancard: 'blacklisted_pancard',
    icon: 'MdOutlineStreetview',
    iconColor: '#cf1332',
    link: '/blacklisted',
  },
}
