export enum Roles {
  SUPER_ADMIN = 'Super Admin',
  ADMIN = 'Admin',
  CREDIT_MANAGER = 'Credit Manager',
  CREDIT_HOD = 'Credit HOD',
  CALLING_HOD = 'Calling HOD',
  OTHER = 'Other',
  COLLECTION_EXECUTIVE = 'Collection Executive',
  DISBURSEMENT_EXECUTIVE = 'Disbursement Executive',
  CREDIT_EXECUTIVE_CPA = 'Credit Executive (CPA)',
  COLLECTION_HOD = 'Collection HOD',
  COLLECTION_TEAM_LEADER = 'Collection Team Leader',
  CALLING_EXECUTIVE = 'Calling Executive',
  MARKETING_EXECUTIVE = 'Marketing Executive',
  ACCOUNTS = 'Accounts',
  MIS = 'MIS',
  TECH_TEAM = 'Tech Team',
  ACCOUNTS_MANAGER = 'Accounts Manager',
  HUMAN_RESOURCES = 'Human Resources',
  SAVE_AGREEMENT = 'save_agreement',
  DSA_CALLER = 'DSA_caller',
  COLLECTION_MANAGER = 'Collection Manager',
  REGIONAL_COLLECTION_MANAGER = 'Regional Collection Manager',
  ACCOUNTS_EXECUTIVE = 'Accounts Executive',
}
